// <auto-generated />
using System;
using DanmakuDownloader.Web.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanmakuDownloader.Web.Migrations
{
    [DbContext(typeof(LocalDatabase))]
    [Migration("20260426100317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DanmakuDownloader.Web.Models.Job.DanmakuJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<int>("Episode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastError");

                    b.Property<DateTime>("NextRunTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("nextRunTime");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retryCount");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("rowVersion");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subjectId");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("targetPath");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextRunTime");

                    b.ToTable("DanmakuJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
